### PR TITLE
Gracefully handle non-absolute path for create-login-profile --filename

### LINKED ISSUE #513: --filename option in v 1.0.X removed or not?
In the docs 
https://crawler.docs.browsertrix.com/user-guide/browser-profiles/#automated-profile-creation-for-user-login 
I can find the parameter --filename

But in the parameters:
https://crawler.docs.browsertrix.com/user-guide/cli-options/
--filename is removed

When I use it in Version 1.0.2 for creating profile it is not working!
Error from the Log File:
`{"timestamp":"2024-03-26T10:16:49.409Z","logLevel":"warn","context":"general","message":"HTTP Error","details":{"type":"exception","message":"Command failed: tar cvfz tiktok_new.tar.gz ./\ntar: .: file changed as we read it\n","stack":"Error: Command failed: tar cvfz tiktok_new.tar.gz ./\ntar: .: file changed as we read it\n\n    at checkExecSyncError (node:child_process:890:11)\n    at Module.execFileSync (node:child_process:926:15)\n    at Browser.saveProfile (file:///app/dist/util/browser.js:111:23)\n    at createProfile (file:///app/dist/create-login-profile.js:212:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InteractiveBrowser.handleRequest (file:///app/dist/create-login-profile.js:435:21)"}}`

Command I used:
docker run -p 6080:6080 -p 9223:9223 -v $PWD/crawls/profiles:/crawls/profiles/ -it webrecorder/browsertrix-crawler:1.0.2 create-login-profile  --filename "tiktok_new.tar.gz" --url "https://tiktok.com" --profile "/crawls/profiles/tiktok.tar.gz"

### PR DESCRIPTION
**Pull request by tw4l**
Fixes #513 

If an absolute path isn't provided to the `create-login-profile` entrypoint's `--filename` option, resolve the value given within `/crawls/profiles`.

Also updates the docs cli-options section to include the `create-login-profile` entrypoint and adjusts the script to automatically generate this page accordingly.

### CODE REVIEW

File: docs/gen-cli.sh [hunk 1]
```diff
@@ -4,11 +4,17 @@ CURR=$(dirname "${BASH_SOURCE[0]}")
...
+echo "" >> $out
+echo "## crawler" >> $out
 echo "" >> $out
 echo '```' >> $out
 #node $CURR/../dist/main.js --help >> $out
 docker run webrecorder/browsertrix-crawler crawl --help >> $out
 echo '```' >> $out
-
-
+echo "" >> $out
```
Comment (ikreymer) [inline docs/gen-cli.sh:15]: Nice!

Comment (ikreymer) [reply docs/gen-cli.sh:15]: (We should also add one for qa + qa docs, but that should be a separate PR)

**Comment by ikreymer** [comment]
Looks good! Tweaked the gen-cli.sh to skip first 3 lines to match the output, and re-generated the options.
