### PR TITLE
crash page on prompt dialog loop to continue:

### LINKED ISSUE #926: Btrix Application Crash due Password
The URL: https://stadlparty.at
presents a httaccess password field

If Browsertrix Crawler V 1.9.2 reaches this page it will crash with  Docker Exit Code: 1

Reproduceable with:

`docker run -d --name test_seed_stadlparty -v /home/user/browsertrix/crawls/:/crawls/    webrecorder/browsertrix-crawler:1.9.2 crawl  --scopeType domain   --headless  --delay 0 --behaviorTimeout 60 --pageLoadTimeout 60 --waitUntil networkidle0  --saveState always   --logging stats,info   --sitemap  --url https://stadlparty.at

`
Log:
```

{"timestamp":"2025-12-01T10:53:45.689Z","logLevel":"info","context":"general","message":"Browsertrix-Crawler 1.9.2 (with warcio.js 2.4.7)","details":{}}
{"timestamp":"2025-12-01T10:53:45.690Z","logLevel":"info","context":"general","message":"Seeds","details":[{"url":"https://stadlparty.at/","scopeType":"domain","include":["/^https?:\\/\\/([^/]+\\.)*stadlparty\\.at\\//"],"exclude":[],"allowHash":false,"depth":-1,"sitemap":"<detect>","auth":null,"_authEncoded":null,"maxExtraHops":0,"maxDepth":1000000}]}
{"timestamp":"2025-12-01T10:53:45.690Z","logLevel":"info","context":"general","message":"Link Selectors","details":[{"selector":"a[href]","extract":"href","isAttribute":false}]}
{"timestamp":"2025-12-01T10:53:45.691Z","logLevel":"info","context":"general","message":"Behavior Options","details":{"message":"{\"autoplay\":true,\"autofetch\":true,\"autoscroll\":true,\"siteSpecific\":true,\"log\":\"__bx_log\",\"startEarly\":true,\"clickSelector\":\"a\"}"}}
{"timestamp":"2025-12-01T10:53:45.756Z","logLevel":"info","context":"sitemap","message":"Fetching sitemap","details":{"from":"<any date>","to":"<any date>"}}
{"timestamp":"2025-12-01T10:53:46.312Z","logLevel":"warn","context":"sitemap","message":"Sitemap for seed failed","details":{"url":"https://stadlparty.at/","sitemap":"<detect>","type":"exception","message":"not found","stack":"Error: not found\n    at SitemapReader.parse (file:///app/dist/util/sitemapper.js:117:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Crawler.parseSitemap (file:///app/dist/crawler.js:1766:13)\n    at async Crawler._addInitialSeeds (file:///app/dist/crawler.js:1194:17)\n    at async Crawler.crawl (file:///app/dist/crawler.js:1117:9)\n    at async Crawler.run (file:///app/dist/crawler.js:386:13)\n    at async file:///app/dist/main.js:58:1"}}
{"timestamp":"2025-12-01T10:53:46.966Z","logLevel":"info","context":"worker","message":"Creating 1 workers","details":{}}
{"timestamp":"2025-12-01T10:53:46.967Z","logLevel":"info","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"timestamp":"2025-12-01T10:53:47.196Z","logLevel":"info","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://stadlparty.at/"}}
{"timestamp":"2025-12-01T10:53:47.198Z","logLevel":"info","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":0,"total":1,"pending":1,"failed":0,"limit":{"max":0,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2025-12-01T10:53:46.969Z\",\"extraHops\":0,\"url\":\"https:\\/\\/stadlparty.at\\/\",\"added\":\"2025-12-01T10:53:45.755Z\",\"depth\":0}"]}}
{"timestamp":"2025-12-01T10:53:47.403Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://stadlparty.at/","workerid":0}}
{"timestamp":"2025-12-01T10:54:47.405Z","logLevel":"warn","context":"pageStatus","message":"Page Load Failed: will retry","details":{"retry":0,"retries":2,"msg":"Navigation timeout of 60000 ms exceeded","url":"https://stadlparty.at/","loadState":0,"page":"https://stadlparty.at/","workerid":0}}
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:79
            this._reject(callback, new TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Page.handleJavaScriptDialog): Target closed
    at CallbackRegistry.clear (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:79:36)
    at CdpCDPSession.onClosed (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CdpSession.js:112:25)
    at Connection.onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:145:25)
    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:37:32)
    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:524:28)
    at Receiver.receiverOnMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:524:28)
    at Immediate.<anonymous> (/app/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:601:16) {
  cause: ProtocolError
      at <instance_members_initializer> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:99:14)
      at new Callback (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:103:16)
      at CallbackRegistry.create (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:22:26)
      at Connection._rawSend (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:104:26)
      at CdpCDPSession.send (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CdpSession.js:71:33)
      at CdpDialog.handle (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Dialog.js:17:28)
      at CdpDialog.dismiss (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Dialog.js:85:20)
      at file:///app/dist/crawler.js:565:30
      at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:36:7
      at Array.map (<anonymous>)
}

Node.js v20.19.5
```

### PR DESCRIPTION
**Pull request by ikreymer**
- if a page is stuck in a window.alert / window.prompt loop, showing >10 or more consecutive dialogs (unrelated to unloading), call Page.crash() to more quickly move on to next page, as not much else can be done.
- add exception handling in dialog accept/dismiss to avoid crawler crash
- fixes #926

Tests:
- Can test with attempting to crawl: https://stadlparty.at/ which has such a loop.

### CODE REVIEW

File: src/crawler.ts [hunk 1]
```diff
@@ -874,30 +874,49 @@ self.__bx_behaviors.selectMainBehavior();
...
+        if (dialog.type() === "beforeunload") {
+          if (opts.pageBlockUnload) {
+            accepted = false;
+          }
         } else {
+          // other JS dialog, just dismiss
+          accepted = false;
+          if (dialogCount >= 10) {
+            // dialog likely in a loop, just ignore
+            logger.warn(
```
Comment (ikreymer) [inline src/crawler.ts]:
```suggestion
            logger.error(
```
