### PR TITLE
fix --overwrite option:

### LINKED ISSUE #997: `--overwrite` should not fail the crawl when directory is empty / missing
Command used:

```
docker run --rm webrecorder/browsertrix-crawler:1.12.2 crawl --seeds https://lovdata.no/ --overwrite
```

Error received:

```
(node:1) ExperimentalWarning: DecompressInterceptor is experimental and subject to change
(Use `node --trace-warnings ...` to show where the warning was created)
{"timestamp":"2026-03-16T22:30:15.925Z","logLevel":"info","context":"general","message":"Browsertrix-Crawler 1.12.2 (with warcio.js 2.4.9)","details":{}}
{"timestamp":"2026-03-16T22:30:15.926Z","logLevel":"info","context":"general","message":"Seeds","details":[{"url":"https://lovdata.no/","normUrl":"https://lovdata.no/","scopeType":"prefix","include":["/^https?:\\/\\/lovdata\\.no\\//"],"exclude":[],"allowHash":false,"depth":-1,"sitemap":null,"auth":null,"_authEncoded":null,"maxExtraHops":0,"maxDepth":1000000}]}
{"timestamp":"2026-03-16T22:30:15.927Z","logLevel":"info","context":"general","message":"Link Selectors","details":[{"selector":"a[href]","extract":"href","isAttribute":false}]}
{"timestamp":"2026-03-16T22:30:15.927Z","logLevel":"info","context":"general","message":"Behavior Options","details":{"message":"{\"autoplay\":true,\"autofetch\":true,\"autoscroll\":true,\"siteSpecific\":true,\"log\":\"__bx_log\",\"startEarly\":true,\"clickSelector\":\"a\"}"}}
{"timestamp":"2026-03-16T22:30:15.932Z","logLevel":"warn","context":"storage","message":"Size check errors","details":{"errors":[{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/crawls/collections/crawl-20260316223015858/archive"}]}}
{"timestamp":"2026-03-16T22:30:16.560Z","logLevel":"info","context":"worker","message":"Creating 1 workers","details":{}}
{"timestamp":"2026-03-16T22:30:16.561Z","logLevel":"info","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"timestamp":"2026-03-16T22:30:16.665Z","logLevel":"info","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://lovdata.no/"}}
{"timestamp":"2026-03-16T22:30:16.666Z","logLevel":"info","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":0,"total":1,"pending":1,"failed":0,"limit":{"max":0,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2026-03-16T22:30:16.562Z\",\"extraHops\":0,\"url\":\"https:\\/\\/lovdata.no\\/\",\"added\":\"2026-03-16T22:30:15.942Z\",\"depth\":0}"]}}
{"timestamp":"2026-03-16T22:30:16.830Z","logLevel":"info","context":"general","message":"Awaiting page load","details":{"page":"https://lovdata.no/","workerid":0}}
node:events:502
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/crawls/collections/crawl-20260316223015858/archive/rec-c264942112b8-crawl-20260316223015858-20260316223017013-0.warc.gz'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/crawls/collections/crawl-20260316223015858/archive/rec-c264942112b8-crawl-20260316223015858-20260316223017013-0.warc.gz'
}

Node.js v20.20.1
```

Expected behavior: do not care about the fact that directory is missing

Nota: this looks like a pretty old bug, at least 1.10.0 already had the issue.

### PR DESCRIPTION
**Pull request by ikreymer**
- fixes #997
- move removing existing crawl dir before disk space check, in case clearing existing crawls frees up more space
- also removes existing crawl dir before creating dirs
- tests: overwrite tests were named incorrectly and were not running, rename

### CODE REVIEW

File: src/crawler.ts [hunk 1]
```diff
@@ -474,6 +474,16 @@ export class Crawler {
   }
 
   async bootstrap() {
+    // check first before disk space check, in case this clears up disk space
```
Comment (tw4l) [inline src/crawler.ts:477]: Good call!
