### PR TITLE
Fix browser network loading

### LINKED ISSUE #960: Crawling does not fetch all images of srcset
I am using browsertrix-crawler:1.7.0 in a docker container.
On my local windows machine I have no problems and all images are fetched, 
but when I try to crawl on a onpremise machine only images fitting the breakpoint for the default windowSize 1360,1020 are fetched.

The images per breakpoint are defined in a srcset.

Do you have a clue, why the behaviour deviates and know a fix, so that all images are crawled?

### PR DESCRIPTION
**Pull request by ikreymer**
When available, async fetch should try to load via the browser network, especially for in-page discovered URLs, to ensure proper credentials are used (may fix #960):

- adds missing CDP param that resulted in browser network being skipped!
- try browser network for direct fetch too, if page is available, but then fallback to node fetch
- default to node fetch when network loading failed, or if in browser (non-page) context for request interception, eg. in a worker.

This complements change webrecorder/browsertrix-behaviors#117 that prefers in-browser fetch when possible.

### CODE REVIEW

File: src/crawler.ts [hunk 1]
```diff
@@ -1201,6 +1201,11 @@ self.__bx_behaviors.selectMainBehavior();
     opts.pageBlockUnload = false;
 
     await this.awaitPageExtraDelay(opts);
+
+    // wait for any browser network fetches to finish before moving on to another page
+    if (recorder) {
+      await recorder.browserFetchQ.onIdle();
+    }
```
Comment (tw4l) [inline src/crawler.ts:1208]: Since `crawlPage` has the possibility of timing out before we reach here, should we also be checking when we first start to crawl a new page that the queue is empty?

Comment (ikreymer) [reply src/crawler.ts:1208]: Hm, I don't think so, as that would eat into the time for that page, as the queue may not be empty.
What will happen is the page-related loading will fail with 'execution context destroyed' errors if they're tied to the previous page, though any not-yet-started requests will be retried async with node fetch anyway, which is similar to current behavior (so may not succeed), but we can avoid those if there is time to wait still allotted for current page.
