### PR TITLE
Catch 4xx and 5xx page.goto() responses to mark invalid URLs as failed

### LINKED ISSUE #207: Success status code on failure
In a [zimit run](https://farm.openzim.org/pipeline/0e178d6329a4e53244f6cc36/debug), we started a crawl of a page `https://journals.openedition.org/bibnum/` which failed after about 15s but the crawler reported a success status code (`0`).

Crawler mentioned `Page Load Failed: https://journals.openedition.org/bibnum/, Reason: Error: Page crashed!`

I am not sure about the exact behavior of the crawler on errors:
- does it halt ?
- if so, on all errors or only certain kinds?
- if not, is there some decision code on whether the crawl is successful: if the error is on the source URL, chances are the output will be unusable because homepage will not be present and/or no links would have been gathered.

Full log follows.

```
Running browsertrix-crawler crawl: crawl --workers 6 --newContext page --waitUntil load,networkidle0 --depth -1 --timeout 90 --behaviors autoplay,autofetch,siteSpecific --behaviorTimeout 90 --url https://journals.openedition.org/bibnum/ --userAgentSuffix +Zimit contact+zimfarm@kiwix.org --cwd /output/.tmp677hzgz2 --statsFilename /output/crawl.json
Note: The newContext argument is deprecated in 0.8.0. Values passed to this option will be ignored
Window context being used to support >1 workers
Set netIdleWait to 2 seconds
Storing state in memory
[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:31.921 (running for 503.0 ms)
[K== Progress:  0 / 0 (100.00%), errors: 0 (0.00%)
[K== Remaining: 0.0 ms (@ 0 pages/second)
[K== Sys. load: 0.0% CPU / 0.0% memory
[K== Workers:   0
[7AText Extraction: Disabled
[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:32.420 (running for 1.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 11.8% CPU / 3.3% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:32.920 (running for 1.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 8.2% CPU / 3.3% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:33.421 (running for 2.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 7.3% CPU / 3.3% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:33.920 (running for 2.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 6.8% CPU / 3.3% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:34.420 (running for 3.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 7.3% CPU / 3.6% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:34.921 (running for 3.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 7.3% CPU / 3.6% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:35.420 (running for 4.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 7.1% CPU / 3.6% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:35.920 (running for 4.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 7.6% CPU / 3.7% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:36.421 (running for 5.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 9.1% CPU / 3.6% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:36.920 (running for 5.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 10.1% CPU / 3.7% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:37.420 (running for 6.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 10.6% CPU / 3.7% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8ALoad Error: https://journals.openedition.org/bibnum/: Navigation failed because browser has disconnected!
[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:37.920 (running for 6.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 12.0% CPU / 3.1% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:38.421 (running for 7.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 11.4% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:38.920 (running for 7.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 11.2% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:39.421 (running for 8.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 10.6% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:39.921 (running for 8.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 10.2% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8Anote: waitForNetworkIdle timed out, ignoring
[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:40.422 (running for 9.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 9.7% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:40.923 (running for 9.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 8.9% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:41.423 (running for 10.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 7.0% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:41.924 (running for 10.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 5.4% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:42.424 (running for 11.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 3.9% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:42.924 (running for 11.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 2.4% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:43.424 (running for 12.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 2.5% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:43.924 (running for 12.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 2.4% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:44.425 (running for 13.0 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 2.3% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:44.925 (running for 13.5 seconds)
[K== Progress:  0 / 1 (0.00%), errors: 0 (0.00%)
[K== Remaining: unknown (@ 0 pages/second)
[K== Sys. load: 2.2% CPU / 3.0% memory
[K== Workers:   1
[K   #0 WORK https://journals.openedition.org/bibnum/
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:281:35)
    at ExecutionContext._ExecutionContext_evaluate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:206:46)
    at ExecutionContext.evaluate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:103:113)
    at IsolatedWorld.evaluate (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/IsolatedWorld.js:171:24)
[8AStarting repair
Page Load Failed: https://journals.openedition.org/bibnum/, Reason: Error: Page crashed!
[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:45.424 (running for 14.0 seconds)
[K== Progress:  1 / 1 (100.00%), errors: 1 (100.00%)
[K== Remaining: 0.0 ms (@ 0.07 pages/second)
[K== Sys. load: 2.6% CPU / 3.1% memory
[K== Workers:   1
[K   #0 IDLE 
[8A[K
[K== Start:     2023-01-21 23:05:31.418
[K== Now:       2023-01-21 23:05:45.439 (running for 14.0 seconds)
[K== Progress:  1 / 1 (100.00%), errors: 1 (100.00%)
[K== Remaining: 0.0 ms (@ 0.07 pages/second)
[K== Sys. load: 2.6% CPU / 3.1% memory
[K== Workers:   1
[K   #0 IDLE 
[8A[8BWaiting to ensure pending data is written to WARCs...
done
```

### LINKED ISSUE #286: Crawler doesn't mark invalid URL as failed
If the crawler is given an invalid URL such as `https://doesntexist.webrecorder.net`, rather than having a failed URL as one would expect, instead the page loads and runs behaviors, is marked as succesfully done, and has a load state of 4 (`BEHAVIORS_DONE`) in the resulting `pages.jsonl`.

### PR DESCRIPTION
**Pull request by tw4l**
Fixes #286 

Also fixes #207 by introducing a `--failOnFailedSeed` CLI option which, when enabled, will fail the crawl with a status code of 1 if there is a page load error on one of the initial seeds.

### CODE REVIEW

**Comment by tw4l** [comment]
@rgaudin, curious to get your eyes on the new proposed CLI option to see if it'll work for your use case!

**Comment by rgaudin** [comment]
@tw4l ; thank you. That looks good 👍

File: crawler.js [hunk 1]
```diff
@@ -941,6 +949,8 @@ export class Crawler {
 
     const logDetails = data.logDetails;
 
+    const failCrawlOnError = (this.isSeedUrl(url) && this.params.failOnFailedSeed);
```
Comment (ikreymer) [inline crawler.js:952]: the isSeedUrl check can just `depth === 0`

File: util/argParser.js [hunk 2]
```diff
@@ -372,6 +372,12 @@ class ArgParser {
         descripe: "If set, write error messages to redis",
         type: "boolean",
         default: false,
+      },
+
+      "failOnFailedSeed": {
+        describe: "If set, crawler will fail with exit code 1 if initial seed fails",
```
Comment (ikreymer) [inline util/argParser.js:378]: I guess this would be if any seed fails, in case there are multiple seeds. But that makes sense to make this an option: fail if any seed fails or not.
I suppose one more would be: fail if all seeds fail, but probably should wait until there's a specific use case for that.
The page list now includes additional info including loadStatus for each page.
